# Hugo Configuration for the Alpha Theme
# This file defines Alpha specific parameters.
#
# It is recommended to place non theme-specific settings, like `baseURL` or 
# `theme = "alpha"` in the root `hugo.toml` file.
#
# Documentation: https://alpha.oxypteros.com/docs/config/hugo-toml/

enableEmoji = true
# Pagination Settings

[pagination]
  disableAliases = false
  pagerSize = 10 # Set the item number before pagination
  path = 'page'


# Markdown Configuration

[markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.extensions]
      strikethrough = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true
      [markup.goldmark.renderHooks.link]
        enableDefault = true
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true

# Code Highlight Settings
[markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    noHl = false
    tabWidth = 2

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "webappmanifest"]
# Tailwind Integration (Build Options) 
#[build]
#  [build.buildStats]
#    enable = true
#  [[build.cachebusters]]
#    source = 'assets/notwatching/hugo_stats\.json'
#    target = 'css'
#  [[build.cachebusters]]
#    source = '(postcss|tailwind)\.config\.js'
#    target = 'css'
#[module]
#  [[module.mounts]]
#    source = 'assets'
#    target = 'assets'
#  [[module.mounts]]
#    disableWatch = true
#    source = 'hugo_stats.json'
#    target = 'assets/notwatching/hugo_stats.json'