# Languages Configuration for the Alpha Theme
# This file defines the primary language and optional multilingual settings for 
# the site.
#
# For multilingual sites, add additional language blocks as shown in the 
# commented example below.
#
# Documentation:
# - Language Settings: https://alpha.oxypteros.com/docs/config/languages-toml/
# - Multilingual Setup: https://alpha.oxypteros.com/docs/multilingual/

# Primary language. Edit for single-langauge site.
[en]
  languageName = "English" 
  languageCode = "en"
  weight = 1 # Lowest number sets the default language

# Uncomment and edit for multilingual
#[fr]
#  languageName = "Français"
#  languageCode = "fr"
#  weight = 2
